{{- if .Values.minio.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: minio
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
type: Opaque
stringData:
  rootUser: {{ .Values.minio.rootUser | quote }}
  rootPassword: {{ .Values.minio.rootPassword | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: {{ .Values.minio.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "app.selectorLabels" (list . "minio") | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "app.commLabels" . | nindent 8 }}
        {{ include "app.selectorLabels" (list . "minio") | nindent 8 }}
    spec:
      containers:
        - name: minio
          image: bitnamilegacy/minio:2025.7.23
          args: ["server", "/data", "--console-address", ":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootUser
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio
                  key: rootPassword
          ports:
            - containerPort: 9000
            - containerPort: 9001
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - |
                    sleep 5
                    mc alias set myminio http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
                    mc mb myminio/{{ .Values.minio.defaultBucket }} --ignore-existing

          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  selector:
    {{ include "app.selectorLabels" (list . "minio") | nindent 4 }}
{{- end }}
