{{- if .Values.postgresql.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.database | quote }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "app.selectorLabels" (list . "postgresql") | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "app.commLabels" . | nindent 8 }}
        {{ include "app.selectorLabels" (list . "postgresql") | nindent 8 }}
    spec:
      containers:
        - name: postgresql
          image: postgres:17.7
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    {{ include "app.commLabels" . | nindent 4 }}
spec:
  ports:
    - port: 5432
  selector:
    {{ include "app.selectorLabels" (list . "postgresql") | nindent 4 }}
{{- end }}
