{{- if $.Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}
type: Opaque
stringData:
  {{- with $.Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
